version: "3" # composeファイルのバージョン
services:
  app: # サービス名
      container_name: go
      build:
        context: .docker
        dockerfile: app.Dockerfile
      tty: true # コンテナの永続化
      volumes:
          - ./app:/go/src/app # マウントディレクトリ

  db:
    image: mysql:8.0
    container_name: 'db'
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d # 初期データ
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: goleran_db
      MYSQL_USER: golearn
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
    ports:
      - '3306:3306'
    restart: always

  api:
    container_name: 'api'
    build:
      context: .docker
      dockerfile: api.Dockerfile
    volumes:
      - ./api:/go/src/api
    environment:
      DSN: goleran_db:password@tcp(db:3306)/goleran_db?charset=utf8mb4&parseTime=True&loc=Local
      ADMIN_NAME: admin
      ADMIN_PASS: password
    ports:
      - '1323:1323'
    # command: './start.sh'
    depends_on:
      db:
        condition: service_started
    tty: true
    stdin_open: true
